"""Explanation Agent (ChainGuard architecture).

Status: **INTERFACE ONLY for the LLM narrative path. The deterministic driver
ranking below is fully implemented and is what the system actually uses.**

The split is deliberate. There are two things "explain the prediction" can mean:

1. **Which drivers moved it, and by how much.** This is a quantitative question
   with a checkable answer, and it is answered here by the attribution layer -
   real SHAP and gradient-times-input values, ranked, with shares of total. This
   is what enters the on-chain payload, because it is reproducible: a verifier
   re-running the pipeline gets the same ranking.

2. **A fluent paragraph describing that.** This is prose generation. It is the
   one part of the architecture that genuinely wants a language model, and it is
   also the one part that must NOT enter the hashed payload - an LLM's output is
   not reproducible, so committing it would make the commitment unverifiable.

So the narrative path is an interface with a deterministic template fallback.
The template produces a readable explanation from the same ranked drivers; a
language model would produce a better-written one, and neither changes a single
number in the prediction.
"""

from __future__ import annotations

from typing import Protocol

import numpy as np
import pandas as pd

from bolt.agents.base import AgentContext, AgentReport, AgentStatus, Evidence, RiskLevel
from bolt.logging_setup import get_logger

log = get_logger(__name__)


class NarrativeBackend(Protocol):
    """Pluggable prose generator. Implement this to attach a language model."""

    def narrate(self, prompt: str) -> str:
        ...


class TemplateNarrator:
    """Deterministic fallback narrator. No model, no API key, no variance."""

    name = "template"

    def narrate(self, prompt: str) -> str:
        return prompt


class ExplanationAgent:
    """Turns attributions and agent reports into a human-readable explanation."""

    name = "Explanation Agent"

    def __init__(self, backend: NarrativeBackend | None = None) -> None:
        self.backend = backend or TemplateNarrator()
        self.llm_attached = backend is not None

    def analyse(
        self,
        context: AgentContext,
        decision: AgentReport,
        reports: list[AgentReport],
        attribution: pd.DataFrame | None = None,
        analogues: list[dict] | None = None,
    ) -> AgentReport:
        drivers = self._rank_drivers(reports, attribution)

        if drivers.empty:
            return AgentReport(
                agent=self.name, risk=decision.risk, score=decision.score,
                confidence=0.0, status=AgentStatus.UNAVAILABLE,
                notes=("no attributions or agent evidence available to explain",),
            )

        text = self._compose(context, decision, reports, drivers, analogues)
        narrative = self.backend.narrate(text)

        evidence = tuple(
            Evidence(
                name=row["driver"], value=float(row["contribution"]), direction=+1,
                weight=float(row["share"]),
                detail=f"{row['driver']}: {row['share']:.0%} of the explained risk",
            )
            for _, row in drivers.head(5).iterrows()
        )

        return AgentReport(
            agent=self.name, risk=decision.risk, score=decision.score,
            confidence=decision.confidence,
            # DEGRADED whenever the prose is template-generated rather than
            # model-written: the ranking is real, the writing is mechanical.
            status=AgentStatus.OK if self.llm_attached else AgentStatus.DEGRADED,
            evidence=evidence,
            notes=(narrative,) if self.llm_attached else (
                narrative,
                "narrative generated by the deterministic template backend; the LLM "
                "narrative path is an interface only in this build (Phase 7). The DRIVER "
                "RANKING above is real attribution output and is unaffected.",
            ),
            extra={
                "narrative_backend": getattr(self.backend, "name", "custom"),
                "top_drivers": drivers.head(5).to_dict("records"),
            },
        )

    @staticmethod
    def _rank_drivers(
        reports: list[AgentReport], attribution: pd.DataFrame | None
    ) -> pd.DataFrame:
        """Prefer real attribution values; fall back to agent evidence weights."""
        if attribution is not None and not attribution.empty:
            column = attribution.columns[0]
            series = attribution[column].sort_values(ascending=False)
            total = float(series.sum()) or 1.0
            return pd.DataFrame({
                "driver": series.index,
                "contribution": series.to_numpy(),
                "share": series.to_numpy() / total,
                "source": "attribution",
            }).reset_index(drop=True)

        rows = []
        for report in reports:
            for item in report.evidence:
                if item.direction > 0:
                    rows.append({"driver": item.name, "contribution": abs(item.weight)})
        if not rows:
            return pd.DataFrame(columns=["driver", "contribution", "share", "source"])

        frame = pd.DataFrame(rows).groupby("driver", as_index=False)["contribution"].sum()
        frame = frame.sort_values("contribution", ascending=False)
        total = float(frame["contribution"].sum()) or 1.0
        frame["share"] = frame["contribution"] / total
        frame["source"] = "agent_evidence"
        return frame.reset_index(drop=True)

    @staticmethod
    def _compose(context, decision, reports, drivers, analogues) -> str:
        """Deterministic explanation assembled from real numbers only."""
        if decision.risk is RiskLevel.INSUFFICIENT_EVIDENCE:
            return (
                f"The system declines to state a risk level for {context.asset} as of "
                f"{context.as_of.date()}. "
                + (decision.notes[0] if decision.notes else "")
            )

        top = drivers.head(5)
        listed = ", ".join(
            f"{row['driver']} ({row['share']:.0%})" for _, row in top.iterrows()
        )
        quant = next((r for r in reports if r.agent == "Quantitative Agent"), None)
        skeptic = next((r for r in reports if r.agent == "Skeptic Agent"), None)

        parts = [
            f"{context.asset} is assessed at {decision.risk.value} risk "
            f"({decision.score:.0f}/100) as of {context.as_of.date()}.",
            f"The primary drivers are {listed}.",
        ]
        if quant is not None and np.isfinite(quant.score):
            probabilities = quant.extra.get("probabilities", {})
            detail = ", ".join(f"{k} {v:.0%}" for k, v in sorted(probabilities.items()))
            parts.append(
                f"The quantitative models estimate a {quant.score / 100:.0%} probability "
                f"of a severe decline ({detail})."
            )
        if skeptic is not None and skeptic.evidence:
            parts.append(
                "Counter-evidence: "
                + "; ".join(e.detail for e in skeptic.top_evidence(2)) + "."
            )
        if analogues:
            from bolt.explain.analogue import summarise_analogues
            parts.append(f"Nearest historical analogue: {summarise_analogues(analogues[:1])}.")
        parts.append(f"Confidence: {decision.confidence:.0%}.")
        return " ".join(parts)
